# Generated by Django 2.2.12 on 2020-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('workpackages', models.TextField(null=True)),
            ],
        ),
    ]
