# Generated by Django 2.2.9 on 2020-07-09 21:13

from django.db import migrations, models
import django.db.models.deletion
import esite.colorfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('kanban_title', models.CharField(max_length=16)),
                ('kanban_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanTag',
            fields=[
                ('kanban_tag_name', models.CharField(max_length=128)),
                ('kanban_tag_icon', models.CharField(max_length=128)),
                ('kanban_tag_color', esite.colorfield.fields.ColorField(max_length=18)),
                ('kanban_tag_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanLane',
            fields=[
                ('kanban_lane_title', models.CharField(max_length=16)),
                ('kanban_lane_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.Kanban')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('kanban_card_title', models.CharField(max_length=16)),
                ('kanban_card_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('kanban_card_description', models.CharField(max_length=256)),
                ('kanban_lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.KanbanLane')),
                ('kanban_tags', models.ManyToManyField(to='kanban.KanbanTag')),
            ],
        ),
    ]
