# Generated by Django 2.2.9 on 2020-06-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('event_scope', models.CharField(blank=True, max_length=256, null=True)),
                ('event_from', models.DateField(blank=True, null=True)),
                ('event_to', models.DateField(blank=True, null=True)),
                ('event_attendees', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
